name: tchira_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  socket_io_client: ^3.1.4
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.9.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0
  # ✅ Ajouté pour la photo de profil
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg